+emr serverless +pyspark scene det ^lane det o/p update
awslabs/autonomous-driving-data-framework pull request #131
Opened 2022-12-24 05:50 UTC by manojrajpurohit

*Issue #, if available:*  N/A

*Description of changes:* 
1. Added EMR Serverless application IaC, it creates an EMR Serverless application. 
2. Updated Scene detection logic using  PySpark native functions. The scene detection logic is generic and thus extensible for any class of object in lane.
3. Updated Lane Detection output format, Before: The lane detection output was persisting a tensor which requires tensor libraries to be imported in any downstream analytics application to read tensor objects. Now: The lane detection output format is a nested list of pixel intensity 0 representing background and 1 representing a lane pixel. Further, the lane detection output writes all lane outputs as rows in a csv file, earlier output format of 1 csv per image is not efficient to be read by downstream analytical applications - small file problem.

**Important Note:**  The pyspark script has a dependency on as JAR spark-dynamodb_2.12 download link -> https://repo1.maven.org/maven2/com/audienceproject/spark-dynamodb_2.12/1.1.1/spark-dynamodb_2.12-1.1.1.jar . This Jar should be manually uploaded to following S3 prefix path s3://addf-ros-image-demo-artifacts-bucket-75fe6115/dags/ros-image-demo/dags-aws/spark_scripts/

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-24 15:20 UTC, dgraeber commented on modules/core/mwaa/requirements/requirements.txt
> +awscli~=1.24.9
the `core/mwaa` module now supports passing in a requirements.txt file to configure MWAA.  Please leverage this capability and not modify the existing code as we need to support backward-compatability

2022-12-24 15:23 UTC, dgraeber requested changes
I can review this after the holidays, but this is missing:

1. a CHANGELOG
2. a workflow in the git modules (`.github/workflows/main.yml`)
3. the deployspec should be handling the upload of the dependency jar as referenced in your PR description
4. VPC support as this is a core module - how do you also support integration with other services?
5. fix.sh and validate.sh should be run...these are unformatted

This PR shouldn't change existing configurations (ref core/mwaa).  I implemented the ability to designate which requirement.txt to install on MWAA and your PR should leverage it.

See me for details?

2022-12-28 14:36 UTC, dgraeber commented on modules/core/emr-serverless/stack.py
> +            iam.PolicyStatement(
To wide open....

2022-12-28 14:36 UTC, dgraeber commented on modules/core/emr-serverless/stack.py
> +            iam.PolicyStatement(
Too wide open

2022-12-28 14:36 UTC, dgraeber commented on modules/core/emr-serverless/stack.py
> +                    cpu="2vCPU",
Should these be configurable?

2022-12-28 14:37 UTC, dgraeber commented on modules/core/emr-serverless/stack.py
> +                    cpu="2vCPU",
Configurable?

2022-12-28 14:38 UTC, dgraeber commented on modules/core/emr-serverless/app.py
> +emr_serverless = EmrServerlessStack(
This should run in a VPC and leverage VPC endpoints?

2022-12-28 14:38 UTC, dgraeber commented on modules/core/emr-serverless/README.md
> +- None
A core module should support VPC integration.

2022-12-28 14:44 UTC, dgraeber commented on modules/analysis/rosbag-image-pipeline/image_dags/ros_image_pipeline.py
> +    start_job_run_op = EmrServerlessStartJobOperator(
This DAG has existed prior to EMR Serverless support...?  If so, is this change backward-compatible?  Will it break the existing pipeline usage?

2023-01-12 14:51 UTC, dgraeber commented
@manojrajpurohit please see above. How would you like to proceed?

2023-01-30 21:50 UTC, dgraeber commented
Closing this PR due to inactivity.  Once a design session / KT session can be conducted and the issues remediated, we can reopen.

2023-01-30 21:50 UTC, closed without merging

2023-07-12 16:55 UTC, srinivasreddych commented
Reopening this PR...

2023-07-19 13:18 UTC, srinivasreddych commented
Closing this in favor of https://github.com/awslabs/idf-modules/pull/29 and eventually splitting the business logic into future PRs