Steps to update `ADDF`
awslabs/autonomous-driving-data-framework pull request #18
Opened 2022-07-20 12:33 UTC by srinivasreddych

*Issue #, if available:*

Steps to update `ADDF`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-20 16:12 UTC, dgraeber approved these changes

2022-07-20 22:10 UTC, chamcca requested changes
I don't think this is the correct update procedure. switching git branches doesn't take into account any changes or customizations users may have made to their local repositories. It also doesn't demonstrate pushing those changes to their local repositories. We need to demonstrate fetching the new upstream release branch, merging into local repo, and pushing those changes to the local.

2022-07-21 01:52 UTC, srinivasreddych commented
> I don't think this is the correct update procedure. switching git branches doesn't take into account any changes or customizations users may have made to their local repositories. It also doesn't demonstrate pushing those changes to their local repositories. We need to demonstrate fetching the new upstream release branch, merging into local repo, and pushing those changes to the local.

This is my thought:
- ADDF team cuts a new release
- user needs to fetch and switch to that release
- they would create a copy of their new `demo` manifests or whatever
- then they do `seedfarmer apply`

Curious to know why do we need to demonstrate a way to `merge` release branch into a`local` branch and push any changes to the `local`? When we cut a new release, dont we intend a user to deploy the release as it is?

2022-07-22 13:52 UTC, srinivasreddych commented
> so, the GitOps process for deploying, maintaining, and updating a customer deployment should be:
> 
>     * `git clone --branch release/MAJOR.MINOR.PATCH --origin upstream git@github.com:awslabs/autonomous-driving-data-framework.git`
> 
>     * customize manifests
> 
>     * customize modules
> 
>     * add own modules
> 
>     * `git commit` changes
> 
>     * `seedfarmer apply [manifest_file]`
> 
>     * `git remote add origin [customer_repo]`
> 
>     * `git push -u origin [current_branch]`
> 
>     * setup CICD to monitor customer repo and execute `seedfarmer apply` on update
> 
> 
> this enables full automation for any changes to manifests or modules. anytime they need to make changes they update and push to their repo.
> 
> the process to update their deployment when a new non-breaking release (MINOR or PATCH) comes out should then be:
> 
>     * `git fetch upstream`
> 
>     * `git merge release/MAJOR.MINOR.PATCH`
> 
>     * resolve any conflicts caused by customizations to local modules
> 
>     * `git commit` changes
> 
>     * `git push`
> 
> 
> this would then trigger the CICD to apply the changes into the environment.

Thanks @chamcca . I was focusing on the second part of your answer, which is, whenever ADDF team releases an update, how would a customer needs to update it. I will add the info accordingly!

2022-07-22 14:47 UTC, chamcca approved these changes

2022-07-22 14:50 UTC, merged